default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: derevo

development:
  <<: *default
  database: ice_development

test:
  <<: *default
  database: ice_test

production:
  <<: *default
  database: ice_development

